### ISSUE TITLE
unable to do intrinsic calibration with high-res cameras

### ISSUE THREAD

**Issue by elhananby** [strawlab/nextgen-camera-users#11]
Hi everyone,
As I mentioned I recently got a couple of new cameras, and whenever I try to do the intrinsic calibration I'm getting a flood of errors:
"Channel full sending frame to process thread. Dropping frame data."
This stops once I remove the checkerboard from the view of the camera.
I assume this has something to do with the high-resolution of the cameras? I guess another option would be to reduce the resolution by using the binning option in Pylon, but then I would also have to do the extrinsic calibration with the same resolution (and the recording of course)?

Thanks

**Comment by astraw** [comment]
I discovered that my implementation was not complete and missing a key flag (to run fast) and a key step (to run the sub-pixel refinement) compared to ROS. I must have inadvertently left these out originally. But now I fixed this in https://github.com/strawlab/strand-braid/commit/a02b44329d98554a7a3fccea3c2fbb55472bf3d5. I have made a new release (0.9.0) which includes these fixes. The new release is in the newly-public strand-braid repo [here](https://github.com/strawlab/strand-braid/releases/tag/braid%2F0.9.0).
